#!/bin/sh /etc/rc.common

USE_PROCD=1
START=96

start_service() {
	local enabled term font_size font_engine hwaccel login seats

	config_load kmscon
	config_get_bool enabled main enabled 0
	[ "$enabled" = 1 ] || return 0

	config_get term main term xterm-256color
	config_get font_size main font_size 14
	config_get font_engine main font_engine 8x16
	config_get_bool hwaccel main hwaccel 1
	config_get login main login "/bin/login -p"
	config_get seats main seats

	procd_open_instance
	procd_set_param command /usr/bin/kmscon --drm --term "$term" \
		--font-size "$font_size" --font-engine "$font_engine" --libseat
	[ "$hwaccel" = 1 ] && procd_append_param command --hwaccel
	[ -n "$seats" ] && procd_append_param command --seats "$seats"
	procd_append_param command --login -- $login
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger kmscon
}
